runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F1

env_variables:
  BUCKET_NAME: "example-gcs-bucket"


handlers:
  - url: /
    static_dir: dist

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
